[package]
name = "condense_db"
version = "0.1.0"
authors = ["Scott Teal"]

[dependencies]
libc = "0.2"
constant_time_eq = "0.1.3"
blake2-rfc = "0.2.18"
libsodium-sys = "0.1.0"
rmp = "^0.8"
rmpv = "^0.4"
byteorder = "1"
